### ISSUE TITLE
TypeError: fullscreen error

### ISSUE THREAD

**Issue by brentrug** [sindresorhus/screenfull.js#122]
Hi,

I get this error:

```
TypeError: fullscreen error
  at Object.<anonymous> (/js/trainer_scripts.js:3176:1323)
  at new Promise (<anonymous>)
  at Object.request (/js/trainer_scripts.js:3176:1127)
  at go_fullscreen (/js/trainer_scripts.js:2118:20)
  at begin_test (/js/trainer_scripts.js:5412:20)
...
(2 additional frame(s) were not displayed)
```

Version:

/*!
* screenfull
* v4.0.1 - 2019-02-18
* (c) Sindre Sorhus; MIT License
*/

Chrome 71.0.3578
browser.name Chrome

Code snippets:
![screencapture-sentry-io-organizations-gurtner-it-solutions-issues-909149567-2019-02-27-08_45_53](https://user-images.githubusercontent.com/6370972/53473980-31545480-3a6c-11e9-932a-bd28e1152cd2.png)

**Comment by brentrug** [comment]
So I figured out, that it happens, when I switch the tab or press ESC...

Then I get this error from Chrome:

`Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`

**Comment by brentrug** [comment]
Issue resolved!

The problem was inside my programming. I called the fullscreen request after some seconds again and a again, which is no problem if one remains in fullscreen. 

But if you change the tab or exit the fullscreen, then in Chrome its not allowed to go into fullscreen without user interaction.
